[package]
name = "protocol_sdk"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"
categories = ["wasm"]
description = """
DANTE protocol stack.
"""
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
near-sdk = "4.0.0-pre.7"